version: '3'

services:
  api:
    container_name: api
    build: docker/go/Dockerfile
    ports:
      - 3000:3000
    links:
      - mysql
    tty:
      true
    volumes:
      - ./src/api:/go/src/api

  mysql:
    container_name: mysql
    build: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./docker/mysql/env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "./mysql_data/mysql:/var/lib/mysql"
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
      - "./docker/mysql/init/:/docker-entrypoint-initdb.d"
