version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    tty:
      true
    volumes:
      - ./src/api:/go/src/api
