version: '3'
services:
  mysql:
    build: ./docker/mysql/
    container_name: mysql
    env_file: ./docker/mysql/.env
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld
    ports:
      - 3306:3306
  app:
    container_name: app
    build: ./docker/app/
    depends_on:
      - mysql
    tty: true
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
volumes:
  mysql-data:
    driver: local
